#
# Module manifest for module 'PSPasswordWolf'
#
# Generated by: Luke Leigh
#
# Generated on: 25/09/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSPasswordWolf.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7fdf0260-0f0e-4d1c-bccc-dba42767143d'

# Author of this module
Author = 'Luke Leigh'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Luke Leigh. All rights reserved.'

# Description of the functionality provided by this module
Description          = 'The PasswordWolf Password Module was created using Invoke-RestMethod to access the https://passwordwolf.com API which then parses the JSON and harvests the generated passwords.
	
I have included all of the options and pre-configured the parameter defaults, replicating the website settings.

"https://passwordwolf.com/api/?length=8&upper=on&lower=on&numbers=off&special=off&repeat=1"

Variable	Values      Default             Description
upper	off/on                          Turns the upper case characters on or off.
lower	off/on                          Turns the lower case characters on or off.
numbers	off/on                          Turns numbers on or off.
special	off/on                          Turns special characters on or off.
length	1-128       15  	        Set the password length.
exclude	[string]    ?!<>li1I08OB	Indicates which characters to exclude.
repeat	1-128       9                   Indicates how many passwords to generate.

More information can be found by visiting the PasswordWolf website - https://passwordwolf.com'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Password','API','PasswordWolf','Create','Generate'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/BanterBoy/PSPasswordWolf/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/BanterBoy/PSPasswordWolf'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/BanterBoy/PSPasswordWolf/wiki'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

